/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qui;

import java.awt.Color;

/**
 *
 * @author Nastia
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Upper = new javax.swing.JPanel();
        WelcomeBill = new javax.swing.JLabel();
        Lower = new javax.swing.JPanel();
        Start = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CreaBill");
        setBackground(new java.awt.Color(51, 0, 0));
        setFont(new java.awt.Font("Bodoni MT Condensed", 0, 18)); // NOI18N
        setIconImages(null);
        setName("WelcomeFrame"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        Upper.setBackground(new java.awt.Color(102, 0, 0));
        Upper.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 8));
        Upper.setName("Upper"); // NOI18N
        Upper.setPreferredSize(new java.awt.Dimension(650, 300));

        WelcomeBill.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 60)); // NOI18N
        WelcomeBill.setForeground(new java.awt.Color(255, 153, 102));
        WelcomeBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WelcomeBill.setText("Welcome to the CreaBill");

        javax.swing.GroupLayout UpperLayout = new javax.swing.GroupLayout(Upper);
        Upper.setLayout(UpperLayout);
        UpperLayout.setHorizontalGroup(
            UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WelcomeBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpperLayout.setVerticalGroup(
            UpperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(WelcomeBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Upper);

        Lower.setBackground(new java.awt.Color(51, 0, 0));
        Lower.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 4));
        Lower.setForeground(new java.awt.Color(204, 204, 204));
        Lower.setName("Upper"); // NOI18N
        Lower.setPreferredSize(new java.awt.Dimension(650, 150));
        Lower.setRequestFocusEnabled(false);
        Lower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LowerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LowerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LowerMouseExited(evt);
            }
        });

        Start.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 36)); // NOI18N
        Start.setForeground(new java.awt.Color(102, 0, 0));
        Start.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Start.setText("START");

        javax.swing.GroupLayout LowerLayout = new javax.swing.GroupLayout(Lower);
        Lower.setLayout(LowerLayout);
        LowerLayout.setHorizontalGroup(
            LowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LowerLayout.setVerticalGroup(
            LowerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(Lower);
        Lower.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LowerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LowerMouseEntered
        Lower.setBackground(new Color(255,153,102));
    }//GEN-LAST:event_LowerMouseEntered

    private void LowerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LowerMouseExited
        Lower.setBackground(new Color(51,0,0));
    }//GEN-LAST:event_LowerMouseExited

    private void LowerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LowerMouseClicked
        // TODO add your handling code here:
        PrimeWindow window = new PrimeWindow();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_LowerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lower;
    private javax.swing.JLabel Start;
    private javax.swing.JPanel Upper;
    private javax.swing.JLabel WelcomeBill;
    // End of variables declaration//GEN-END:variables
}
