# docker-compose build
# docker-compose up

version: "3.8"

services:
   postgres:
      image: postgres:13
      ports:
         - 5432:5432
      volumes:
         - db:/data/postgres
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: eshop
         PGDATA: /data/postgres
      restart: unless-stopped
      networks:
         - backend

   node:
      depends_on:
         - postgres
      build: ./nodejs_part
      restart: unless-stopped
      ports:
         - 8080:8080
      networks:
         - backend
         - frontend
      links:
         - postgres

   react:
      depends_on:
         - node
      build: ./react_part
      ports:
         - 3000:3000
      networks:
         - frontend

volumes:
   db:

networks:
   backend:
   frontend:
